// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace KelpNet.Tools
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AttributeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(21, Name = @"ref_attr_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RefAttrName
        {
            get { return __pbn__RefAttrName ?? ""; }
            set { __pbn__RefAttrName = value; }
        }
        public bool ShouldSerializeRefAttrName() => __pbn__RefAttrName != null;
        public void ResetRefAttrName() => __pbn__RefAttrName = null;
        private string __pbn__RefAttrName;

        [global::ProtoBuf.ProtoMember(13, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

        [global::ProtoBuf.ProtoMember(20, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(AttributeType.Undefined)]
        public AttributeType Type
        {
            get { return __pbn__Type ?? AttributeType.Undefined; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private AttributeType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"f")]
        public float F
        {
            get { return __pbn__F.GetValueOrDefault(); }
            set { __pbn__F = value; }
        }
        public bool ShouldSerializeF() => __pbn__F != null;
        public void ResetF() => __pbn__F = null;
        private float? __pbn__F;

        [global::ProtoBuf.ProtoMember(3, Name = @"i")]
        public long I
        {
            get { return __pbn__I.GetValueOrDefault(); }
            set { __pbn__I = value; }
        }
        public bool ShouldSerializeI() => __pbn__I != null;
        public void ResetI() => __pbn__I = null;
        private long? __pbn__I;

        [global::ProtoBuf.ProtoMember(4, Name = @"s")]
        public byte[] S
        {
            get { return __pbn__S; }
            set { __pbn__S = value; }
        }
        public bool ShouldSerializeS() => __pbn__S != null;
        public void ResetS() => __pbn__S = null;
        private byte[] __pbn__S;

        [global::ProtoBuf.ProtoMember(5, Name = @"t")]
        public TensorProto T { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"g")]
        public GraphProto G { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"sparse_tensor")]
        public SparseTensorProto SparseTensor { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"floats")]
        public float[] Floats { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"ints")]
        public long[] Ints { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"strings")]
        public global::System.Collections.Generic.List<byte[]> Strings { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(10, Name = @"tensors")]
        public global::System.Collections.Generic.List<TensorProto> Tensors { get; } = new global::System.Collections.Generic.List<TensorProto>();

        [global::ProtoBuf.ProtoMember(11, Name = @"graphs")]
        public global::System.Collections.Generic.List<GraphProto> Graphs { get; } = new global::System.Collections.Generic.List<GraphProto>();

        [global::ProtoBuf.ProtoMember(23, Name = @"sparse_tensors")]
        public global::System.Collections.Generic.List<SparseTensorProto> SparseTensors { get; } = new global::System.Collections.Generic.List<SparseTensorProto>();

        [global::ProtoBuf.ProtoContract()]
        public enum AttributeType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNDEFINED")]
            Undefined = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOAT")]
            Float = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"INT")]
            Int = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"STRING")]
            String = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TENSOR")]
            Tensor = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"GRAPH")]
            Graph = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"SPARSE_TENSOR")]
            SparseTensor = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOATS")]
            Floats = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"INTS")]
            Ints = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"STRINGS")]
            Strings = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"TENSORS")]
            Tensors = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"GRAPHS")]
            Graphs = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"SPARSE_TENSORS")]
            SparseTensors = 12,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ValueInfoProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public TypeProto Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NodeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"input")]
        public global::System.Collections.Generic.List<string> Inputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"output")]
        public global::System.Collections.Generic.List<string> Outputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(4, Name = @"op_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OpType
        {
            get { return __pbn__OpType ?? ""; }
            set { __pbn__OpType = value; }
        }
        public bool ShouldSerializeOpType() => __pbn__OpType != null;
        public void ResetOpType() => __pbn__OpType = null;
        private string __pbn__OpType;

        [global::ProtoBuf.ProtoMember(7, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain
        {
            get { return __pbn__Domain ?? ""; }
            set { __pbn__Domain = value; }
        }
        public bool ShouldSerializeDomain() => __pbn__Domain != null;
        public void ResetDomain() => __pbn__Domain = null;
        private string __pbn__Domain;

        [global::ProtoBuf.ProtoMember(5, Name = @"attribute")]
        public global::System.Collections.Generic.List<AttributeProto> Attributes { get; } = new global::System.Collections.Generic.List<AttributeProto>();

        [global::ProtoBuf.ProtoMember(6, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrainingInfoProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"initialization")]
        public GraphProto Initialization { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"algorithm")]
        public GraphProto Algorithm { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"initialization_binding")]
        public global::System.Collections.Generic.List<StringStringEntryProto> InitializationBindings { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

        [global::ProtoBuf.ProtoMember(4, Name = @"update_binding")]
        public global::System.Collections.Generic.List<StringStringEntryProto> UpdateBindings { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModelProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ir_version")]
        public long IrVersion
        {
            get { return __pbn__IrVersion.GetValueOrDefault(); }
            set { __pbn__IrVersion = value; }
        }
        public bool ShouldSerializeIrVersion() => __pbn__IrVersion != null;
        public void ResetIrVersion() => __pbn__IrVersion = null;
        private long? __pbn__IrVersion;

        [global::ProtoBuf.ProtoMember(8, Name = @"opset_import")]
        public global::System.Collections.Generic.List<OperatorSetIdProto> OpsetImports { get; } = new global::System.Collections.Generic.List<OperatorSetIdProto>();

        [global::ProtoBuf.ProtoMember(2, Name = @"producer_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProducerName
        {
            get { return __pbn__ProducerName ?? ""; }
            set { __pbn__ProducerName = value; }
        }
        public bool ShouldSerializeProducerName() => __pbn__ProducerName != null;
        public void ResetProducerName() => __pbn__ProducerName = null;
        private string __pbn__ProducerName;

        [global::ProtoBuf.ProtoMember(3, Name = @"producer_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProducerVersion
        {
            get { return __pbn__ProducerVersion ?? ""; }
            set { __pbn__ProducerVersion = value; }
        }
        public bool ShouldSerializeProducerVersion() => __pbn__ProducerVersion != null;
        public void ResetProducerVersion() => __pbn__ProducerVersion = null;
        private string __pbn__ProducerVersion;

        [global::ProtoBuf.ProtoMember(4, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain
        {
            get { return __pbn__Domain ?? ""; }
            set { __pbn__Domain = value; }
        }
        public bool ShouldSerializeDomain() => __pbn__Domain != null;
        public void ResetDomain() => __pbn__Domain = null;
        private string __pbn__Domain;

        [global::ProtoBuf.ProtoMember(5, Name = @"model_version")]
        public long ModelVersion
        {
            get { return __pbn__ModelVersion.GetValueOrDefault(); }
            set { __pbn__ModelVersion = value; }
        }
        public bool ShouldSerializeModelVersion() => __pbn__ModelVersion != null;
        public void ResetModelVersion() => __pbn__ModelVersion = null;
        private long? __pbn__ModelVersion;

        [global::ProtoBuf.ProtoMember(6, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

        [global::ProtoBuf.ProtoMember(7, Name = @"graph")]
        public GraphProto Graph { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"metadata_props")]
        public global::System.Collections.Generic.List<StringStringEntryProto> MetadataProps { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

        [global::ProtoBuf.ProtoMember(20, Name = @"training_info")]
        public global::System.Collections.Generic.List<TrainingInfoProto> TrainingInfoes { get; } = new global::System.Collections.Generic.List<TrainingInfoProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StringStringEntryProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key
        {
            get { return __pbn__Key ?? ""; }
            set { __pbn__Key = value; }
        }
        public bool ShouldSerializeKey() => __pbn__Key != null;
        public void ResetKey() => __pbn__Key = null;
        private string __pbn__Key;

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value
        {
            get { return __pbn__Value ?? ""; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private string __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TensorAnnotation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tensor_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TensorName
        {
            get { return __pbn__TensorName ?? ""; }
            set { __pbn__TensorName = value; }
        }
        public bool ShouldSerializeTensorName() => __pbn__TensorName != null;
        public void ResetTensorName() => __pbn__TensorName = null;
        private string __pbn__TensorName;

        [global::ProtoBuf.ProtoMember(2, Name = @"quant_parameter_tensor_names")]
        public global::System.Collections.Generic.List<StringStringEntryProto> QuantParameterTensorNames { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GraphProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node")]
        public global::System.Collections.Generic.List<NodeProto> Nodes { get; } = new global::System.Collections.Generic.List<NodeProto>();

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(5, Name = @"initializer")]
        public global::System.Collections.Generic.List<TensorProto> Initializers { get; } = new global::System.Collections.Generic.List<TensorProto>();

        [global::ProtoBuf.ProtoMember(15, Name = @"sparse_initializer")]
        public global::System.Collections.Generic.List<SparseTensorProto> SparseInitializers { get; } = new global::System.Collections.Generic.List<SparseTensorProto>();

        [global::ProtoBuf.ProtoMember(10, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

        [global::ProtoBuf.ProtoMember(11, Name = @"input")]
        public global::System.Collections.Generic.List<ValueInfoProto> Inputs { get; } = new global::System.Collections.Generic.List<ValueInfoProto>();

        [global::ProtoBuf.ProtoMember(12, Name = @"output")]
        public global::System.Collections.Generic.List<ValueInfoProto> Outputs { get; } = new global::System.Collections.Generic.List<ValueInfoProto>();

        [global::ProtoBuf.ProtoMember(13, Name = @"value_info")]
        public global::System.Collections.Generic.List<ValueInfoProto> ValueInfoes { get; } = new global::System.Collections.Generic.List<ValueInfoProto>();

        [global::ProtoBuf.ProtoMember(14, Name = @"quantization_annotation")]
        public global::System.Collections.Generic.List<TensorAnnotation> QuantizationAnnotations { get; } = new global::System.Collections.Generic.List<TensorAnnotation>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TensorProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dims")]
        public long[] Dims { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int data_type
        {
            get { return __pbn__data_type.GetValueOrDefault(); }
            set { __pbn__data_type = value; }
        }
        public bool ShouldSerializedata_type() => __pbn__data_type != null;
        public void Resetdata_type() => __pbn__data_type = null;
        private int? __pbn__data_type;

        [global::ProtoBuf.ProtoMember(3)]
        public Segment segment { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"float_data", IsPacked = true)]
        public float[] FloatDatas { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"int32_data", IsPacked = true)]
        public int[] Int32Datas { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"string_data")]
        public global::System.Collections.Generic.List<byte[]> StringDatas { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(7, Name = @"int64_data", IsPacked = true)]
        public long[] Int64Datas { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(12, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

        [global::ProtoBuf.ProtoMember(9, Name = @"raw_data")]
        public byte[] RawData
        {
            get { return __pbn__RawData; }
            set { __pbn__RawData = value; }
        }
        public bool ShouldSerializeRawData() => __pbn__RawData != null;
        public void ResetRawData() => __pbn__RawData = null;
        private byte[] __pbn__RawData;

        [global::ProtoBuf.ProtoMember(13, Name = @"external_data")]
        public global::System.Collections.Generic.List<StringStringEntryProto> ExternalDatas { get; } = new global::System.Collections.Generic.List<StringStringEntryProto>();

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue(DataLocation.Default)]
        public DataLocation data_location
        {
            get { return __pbn__data_location ?? DataLocation.Default; }
            set { __pbn__data_location = value; }
        }
        public bool ShouldSerializedata_location() => __pbn__data_location != null;
        public void Resetdata_location() => __pbn__data_location = null;
        private DataLocation? __pbn__data_location;

        [global::ProtoBuf.ProtoMember(10, Name = @"double_data", IsPacked = true)]
        public double[] DoubleDatas { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"uint64_data", IsPacked = true)]
        public ulong[] Uint64Datas { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Segment : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"begin")]
            public long Begin
            {
                get { return __pbn__Begin.GetValueOrDefault(); }
                set { __pbn__Begin = value; }
            }
            public bool ShouldSerializeBegin() => __pbn__Begin != null;
            public void ResetBegin() => __pbn__Begin = null;
            private long? __pbn__Begin;

            [global::ProtoBuf.ProtoMember(2, Name = @"end")]
            public long End
            {
                get { return __pbn__End.GetValueOrDefault(); }
                set { __pbn__End = value; }
            }
            public bool ShouldSerializeEnd() => __pbn__End != null;
            public void ResetEnd() => __pbn__End = null;
            private long? __pbn__End;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum DataType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNDEFINED")]
            Undefined = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOAT")]
            Float = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"UINT8")]
            Uint8 = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"INT8")]
            Int8 = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"UINT16")]
            Uint16 = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"INT16")]
            Int16 = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"INT32")]
            Int32 = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"INT64")]
            Int64 = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"STRING")]
            String = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"BOOL")]
            Bool = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOAT16")]
            Float16 = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"DOUBLE")]
            Double = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"UINT32")]
            Uint32 = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"UINT64")]
            Uint64 = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLEX64")]
            Complex64 = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLEX128")]
            Complex128 = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"BFLOAT16")]
            Bfloat16 = 16,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum DataLocation
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DEFAULT")]
            Default = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"EXTERNAL")]
            External = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SparseTensorProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"values")]
        public TensorProto Values { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"indices")]
        public TensorProto Indices { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dims")]
        public long[] Dims { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TensorShapeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dim")]
        public global::System.Collections.Generic.List<Dimension> Dims { get; } = new global::System.Collections.Generic.List<Dimension>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Dimension : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"dim_value")]
            public long DimValue
            {
                get { return __pbn__value.Is(1) ? __pbn__value.Int64 : default; }
                set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(1, value); }
            }
            public bool ShouldSerializeDimValue() => __pbn__value.Is(1);
            public void ResetDimValue() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 1);

            private global::ProtoBuf.DiscriminatedUnion64Object __pbn__value;

            [global::ProtoBuf.ProtoMember(2, Name = @"dim_param")]
            [global::System.ComponentModel.DefaultValue("")]
            public string DimParam
            {
                get { return __pbn__value.Is(2) ? ((string)__pbn__value.Object) : ""; }
                set { __pbn__value = new global::ProtoBuf.DiscriminatedUnion64Object(2, value); }
            }
            public bool ShouldSerializeDimParam() => __pbn__value.Is(2);
            public void ResetDimParam() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__value, 2);

            [global::ProtoBuf.ProtoMember(3, Name = @"denotation")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Denotation
            {
                get { return __pbn__Denotation ?? ""; }
                set { __pbn__Denotation = value; }
            }
            public bool ShouldSerializeDenotation() => __pbn__Denotation != null;
            public void ResetDenotation() => __pbn__Denotation = null;
            private string __pbn__Denotation;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TypeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tensor_type")]
        public Tensor TensorType
        {
            get { return __pbn__value.Is(1) ? ((Tensor)__pbn__value.Object) : default; }
            set { __pbn__value = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeTensorType() => __pbn__value.Is(1);
        public void ResetTensorType() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__value, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__value;

        [global::ProtoBuf.ProtoMember(4, Name = @"sequence_type")]
        public Sequence SequenceType
        {
            get { return __pbn__value.Is(4) ? ((Sequence)__pbn__value.Object) : default; }
            set { __pbn__value = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeSequenceType() => __pbn__value.Is(4);
        public void ResetSequenceType() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__value, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"map_type")]
        public Map MapType
        {
            get { return __pbn__value.Is(5) ? ((Map)__pbn__value.Object) : default; }
            set { __pbn__value = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializeMapType() => __pbn__value.Is(5);
        public void ResetMapType() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__value, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"denotation")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Denotation
        {
            get { return __pbn__Denotation ?? ""; }
            set { __pbn__Denotation = value; }
        }
        public bool ShouldSerializeDenotation() => __pbn__Denotation != null;
        public void ResetDenotation() => __pbn__Denotation = null;
        private string __pbn__Denotation;

        [global::ProtoBuf.ProtoContract()]
        public partial class Tensor : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"elem_type")]
            public int ElemType
            {
                get { return __pbn__ElemType.GetValueOrDefault(); }
                set { __pbn__ElemType = value; }
            }
            public bool ShouldSerializeElemType() => __pbn__ElemType != null;
            public void ResetElemType() => __pbn__ElemType = null;
            private int? __pbn__ElemType;

            [global::ProtoBuf.ProtoMember(2, Name = @"shape")]
            public TensorShapeProto Shape { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Sequence : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"elem_type")]
            public TypeProto ElemType { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Map : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"key_type")]
            public int KeyType
            {
                get { return __pbn__KeyType.GetValueOrDefault(); }
                set { __pbn__KeyType = value; }
            }
            public bool ShouldSerializeKeyType() => __pbn__KeyType != null;
            public void ResetKeyType() => __pbn__KeyType = null;
            private int? __pbn__KeyType;

            [global::ProtoBuf.ProtoMember(2, Name = @"value_type")]
            public TypeProto ValueType { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperatorSetIdProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain
        {
            get { return __pbn__Domain ?? ""; }
            set { __pbn__Domain = value; }
        }
        public bool ShouldSerializeDomain() => __pbn__Domain != null;
        public void ResetDomain() => __pbn__Domain = null;
        private string __pbn__Domain;

        [global::ProtoBuf.ProtoMember(2, Name = @"version")]
        public long Version
        {
            get { return __pbn__Version.GetValueOrDefault(); }
            set { __pbn__Version = value; }
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private long? __pbn__Version;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FunctionProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"since_version")]
        public long SinceVersion
        {
            get { return __pbn__SinceVersion.GetValueOrDefault(); }
            set { __pbn__SinceVersion = value; }
        }
        public bool ShouldSerializeSinceVersion() => __pbn__SinceVersion != null;
        public void ResetSinceVersion() => __pbn__SinceVersion = null;
        private long? __pbn__SinceVersion;

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        [global::System.ComponentModel.DefaultValue(OperatorStatus.Experimental)]
        public OperatorStatus Status
        {
            get { return __pbn__Status ?? OperatorStatus.Experimental; }
            set { __pbn__Status = value; }
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private OperatorStatus? __pbn__Status;

        [global::ProtoBuf.ProtoMember(4, Name = @"input")]
        public global::System.Collections.Generic.List<string> Inputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5, Name = @"output")]
        public global::System.Collections.Generic.List<string> Outputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(6, Name = @"attribute")]
        public global::System.Collections.Generic.List<string> Attributes { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(7, Name = @"node")]
        public global::System.Collections.Generic.List<NodeProto> Nodes { get; } = new global::System.Collections.Generic.List<NodeProto>();

        [global::ProtoBuf.ProtoMember(8, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

        [global::ProtoBuf.ProtoMember(9, Name = @"opset_import")]
        public global::System.Collections.Generic.List<OperatorSetIdProto> OpsetImports { get; } = new global::System.Collections.Generic.List<OperatorSetIdProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperatorProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"op_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OpType
        {
            get { return __pbn__OpType ?? ""; }
            set { __pbn__OpType = value; }
        }
        public bool ShouldSerializeOpType() => __pbn__OpType != null;
        public void ResetOpType() => __pbn__OpType = null;
        private string __pbn__OpType;

        [global::ProtoBuf.ProtoMember(2, Name = @"since_version")]
        public long SinceVersion
        {
            get { return __pbn__SinceVersion.GetValueOrDefault(); }
            set { __pbn__SinceVersion = value; }
        }
        public bool ShouldSerializeSinceVersion() => __pbn__SinceVersion != null;
        public void ResetSinceVersion() => __pbn__SinceVersion = null;
        private long? __pbn__SinceVersion;

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        [global::System.ComponentModel.DefaultValue(OperatorStatus.Experimental)]
        public OperatorStatus Status
        {
            get { return __pbn__Status ?? OperatorStatus.Experimental; }
            set { __pbn__Status = value; }
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private OperatorStatus? __pbn__Status;

        [global::ProtoBuf.ProtoMember(10, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperatorSetProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"magic")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Magic
        {
            get { return __pbn__Magic ?? ""; }
            set { __pbn__Magic = value; }
        }
        public bool ShouldSerializeMagic() => __pbn__Magic != null;
        public void ResetMagic() => __pbn__Magic = null;
        private string __pbn__Magic;

        [global::ProtoBuf.ProtoMember(2, Name = @"ir_version")]
        public long IrVersion
        {
            get { return __pbn__IrVersion.GetValueOrDefault(); }
            set { __pbn__IrVersion = value; }
        }
        public bool ShouldSerializeIrVersion() => __pbn__IrVersion != null;
        public void ResetIrVersion() => __pbn__IrVersion = null;
        private long? __pbn__IrVersion;

        [global::ProtoBuf.ProtoMember(3, Name = @"ir_version_prerelease")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IrVersionPrerelease
        {
            get { return __pbn__IrVersionPrerelease ?? ""; }
            set { __pbn__IrVersionPrerelease = value; }
        }
        public bool ShouldSerializeIrVersionPrerelease() => __pbn__IrVersionPrerelease != null;
        public void ResetIrVersionPrerelease() => __pbn__IrVersionPrerelease = null;
        private string __pbn__IrVersionPrerelease;

        [global::ProtoBuf.ProtoMember(7, Name = @"ir_build_metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IrBuildMetadata
        {
            get { return __pbn__IrBuildMetadata ?? ""; }
            set { __pbn__IrBuildMetadata = value; }
        }
        public bool ShouldSerializeIrBuildMetadata() => __pbn__IrBuildMetadata != null;
        public void ResetIrBuildMetadata() => __pbn__IrBuildMetadata = null;
        private string __pbn__IrBuildMetadata;

        [global::ProtoBuf.ProtoMember(4, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain
        {
            get { return __pbn__Domain ?? ""; }
            set { __pbn__Domain = value; }
        }
        public bool ShouldSerializeDomain() => __pbn__Domain != null;
        public void ResetDomain() => __pbn__Domain = null;
        private string __pbn__Domain;

        [global::ProtoBuf.ProtoMember(5, Name = @"opset_version")]
        public long OpsetVersion
        {
            get { return __pbn__OpsetVersion.GetValueOrDefault(); }
            set { __pbn__OpsetVersion = value; }
        }
        public bool ShouldSerializeOpsetVersion() => __pbn__OpsetVersion != null;
        public void ResetOpsetVersion() => __pbn__OpsetVersion = null;
        private long? __pbn__OpsetVersion;

        [global::ProtoBuf.ProtoMember(6, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString
        {
            get { return __pbn__DocString ?? ""; }
            set { __pbn__DocString = value; }
        }
        public bool ShouldSerializeDocString() => __pbn__DocString != null;
        public void ResetDocString() => __pbn__DocString = null;
        private string __pbn__DocString;

        [global::ProtoBuf.ProtoMember(8, Name = @"operator")]
        public global::System.Collections.Generic.List<OperatorProto> Operators { get; } = new global::System.Collections.Generic.List<OperatorProto>();

        [global::ProtoBuf.ProtoMember(9, Name = @"functions")]
        public global::System.Collections.Generic.List<FunctionProto> Functions { get; } = new global::System.Collections.Generic.List<FunctionProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum Version
    {
        [global::ProtoBuf.ProtoEnum(Name = @"_START_VERSION")]
        StartVersion = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2017_10_10")]
        IrVersion20171010 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2017_10_30")]
        IrVersion20171030 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2017_11_3")]
        IrVersion2017113 = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2019_1_22")]
        IrVersion2019122 = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2019_3_18")]
        IrVersion2019318 = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION_2019_9_19")]
        IrVersion2019919 = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"IR_VERSION")]
        IrVersion = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OperatorStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EXPERIMENTAL")]
        Experimental = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STABLE")]
        Stable = 1,
    }

}